agent_specs:
  batch_design: true
clip_epsilon: 0.2
delta: 0.5
env_name: robo-sumo-devants-v0
gamma: 0.995
l2_reg: 0.001
max_epoch_num: 1000
min_batch_size: 50000
mini_batch_size: 2048
num_optim_epoch: 10
policy_lr: 5.0e-05
policy_momentum: 0.0
policy_optimizer: Adam
dev_policy_specs:
  control_fix_control_std: false
  control_htype: tanh
  control_log_std: 0
  control_mlp:
  - 64
  - 128
  - 64
  scale_fix_control_std: false
  scale_htype: tanh
  scale_log_std: 0
  scale_mlp:
  - 64
  - 64
policy_weightdecay: 0.0
runner_type: multi-evo-agent-runner
save_model_interval: 1
seed: 42
tau: 0.95
termination_epoch: 1000
use_entire_obs: false
use_exploration_curriculum: true
use_opponent_sample: true
use_parse_reward: true
use_reward_scaling: false
value_lr: 0.0003
value_momentum: 0.0
value_optimizer: Adam
dev_value_specs:
  htype: tanh
  mlp:
  - 64
  - 64
  - 64
value_weightdecay: 0.0
