params:
  seed: ${...seed}

  algo:
    name: self_play_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [ 256, 128, 64 ]
      activation: elu
      d2rl: False

      initializer:
        name: default
  # self play agent related
  player_pool_type: ${...player_pool_type}
  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load
  op_load_path: ${if:${...op_checkpoint},${...op_checkpoint},${...checkpoint}} # default play with myself
  num_agents: ${...num_agents}

  update_win_rate: 0.7
  player_pool_length: 2
  games_to_check: 400
  max_update_steps: 5000
  device: ${...rl_device}
  config:
    name: ${resolve_default:MA_Ant_1v1,${....experiment}}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:100000,${....max_iterations}}
    save_best_after: 200
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16 #64
    minibatch_size: ${resolve_default:32768,${....minibatch_size}}
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    use_smooth_clamp: True
    bounds_loss_coef: 0.0000
    player:
      games_num: 4000
      record_elo: True
      init_elo: 400