params:
  seed: ${...seed}

  algo:
    name: self_play_transform2act

  model:
    name: transform2act

  network:
    name: transform2act
    attr_fixed_dim: 4
    attr_design_dim: 5
    gym_obs_dim: 26
    enable_remove: ${....task.robot.enable_remove}
    control_action_dim: 1

    policy_specs:
      htype: tanh
      skel_gnn_specs:
        layer_type: graph_conv
        hdims: [64, 64, 64]
        aggr: add
        bias: true
      skel_index_mlp:
        hdims: [128, 128]
        rescale_linear: true
      control_gnn_specs:
        layer_type: graph_conv
        hdims: [64, 64, 64]
        aggr: add
        bias: true
      control_index_mlp:
        hdims: [128, 128]
        rescale_linear: true
      attr_gnn_specs:
        layer_type: graph_conv
        hdims: [64, 64, 64]
        aggr: add
        bias: true
      attr_index_mlp:
        hdims: [128, 128]
        rescale_linear: true
      control_log_std: 0
      attr_log_std: -2.3
      fix_control_std: false
      fix_attr_std: false
    
    value_specs:
      htype: tanh
      design_flag_in_state: true
      onehot_design_flag: true
      mlp: [512, 256]
      gnn_specs:
        layer_type: graph_conv
        hdims: [64, 64, 64]
        aggr: add
        bias: true

  # self play agent related
  player_pool_type: ${resolve_default:evo,${...player_pool_type}}
  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load
  op_load_path: ${if:${...op_checkpoint},${...op_checkpoint},${...checkpoint}} # default play with myself
  num_agents: ${...num_agents}

  update_win_rate: 0.7
  player_pool_length: 2
  games_to_check: 400
  max_update_steps: 5000
  device: ${...rl_device}
  config:
    name: ${resolve_default:MA_EvoAnt_1v1,${....experiment}}
    env_name: evo_rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: False # actually already normed by default
    normalize_value: False # actually already normed by default
    value_bootstrap: True
    clip_actions: False
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: '' # standard
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:100000,${....max_iterations}}
    save_best_after: 200
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: ${resolve_default:32768,${....minibatch_size}}
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    use_smooth_clamp: True
    bounds_loss_coef: 0.0000
    player:
      games_num: 4000
      record_elo: True
      init_elo: 400