ALGO: mappo
CFG_DEST: config.yaml
CHECKPOINT_PERIOD: 10
COMPETEVO:
  NUM_ENV_STEPS: 10000000.0
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  N_ROLLOUT_THREADS: 1
  N_TRAINING_THREADS: 1
CUDNN:
  DETERMINISTIC: true
DEVICE: cuda:0
ENV:
  AGENT_NAMES:
  - evo_ant_fighter
  - evo_ant_fighter
  EPISODE_LENGTH: 500
  INIT_POS:
  - - -1
    - 0
    - 2.5
  - - 1
    - 0
    - 2.5
  MAX_RADIUS: 4
  MIN_RADIUS: 4
  WORLD_XML_PATH: ./competevo/evo_envs/assets/world_body_arena.xml
ENV_NAME: SumoEvoAnts-v0
EVAL_PERIOD: 10
IFI: 0.01
LOG_PERIOD: 1
MAPPO:
  CLIP_PARAM: 0.2
  CRITIC_LR: 0.0005
  ENTROPY_COEF: 0.01
  GAE_LAMBDA: 0.95
  GAMMA: 0.99
  HUBER_DELTA: 10
  LR: 0.0005
  MAX_GRAD_NORM: 10.0
  NUM_MINI_BATCH: 1
  OPTI_EPS: 1.0e-05
  PPO_EPOCH: 15
  USE_CLIPPED_VALUE_LOSS: true
  USE_FEATURE_NORMALIZATION: true
  USE_GAE: true
  USE_HUBER_LOSS: true
  USE_LINEAR_LR_DECAY: false
  USE_MAX_GRAD_NORM: true
  USE_POLICY_ACTIVE_MASKS: true
  USE_POPART: false
  USE_PROPER_TIME_LIMITS: false
  USE_VALUENORM: true
  USE_VALUE_ACTIVE_MASKS: true
  VALUE_LOSS_COEF: 0.5
  WEIGHT_DECAY: 0
NETWORK:
  DATA_CHUNK_LENGTH: 10
  GAIN: 0.01
  HIDDEN_SIZE: 64
  LAYER_N: 2
  RECURRENT_N: 1
  SHARE_POLICY: false
  STACKED_FRAMES: 1
  USE_CENTRALIZED_V: true
  USE_NAIVE_RECURRENT_POLICY: false
  USE_ORTHOGONAL: true
  USE_RECURRENT_POLICY: false
  USE_RELU: false
  USE_STACKED_FRAMES: false
OUT_DIR: ./tmp
RENDER_EPISODES: 1
RNG_SEED: 42
SAVE_VIDEO: true
USER_NAME: competevo
USE_EVAL: true
USE_GPU: true
USE_OBS_INSTEAD_OF_STATE: false
USE_RENDER: false
XML:
  FILTER_PARENT: enable
  GEOM_CONDIM: 3
  GEOM_FRICTION:
  - 0.7
  - 0.1
  - 0.1
  SHADOWCLIP: 0.5
