ENV_NAME: "MultiHalfCheetah-v0"
TEMPLATE: "./envs/assets/multi_half_cheetah.xml"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

ENV:
  EPISODE_LENGTH: 1000
  DIMENSION: 2
  FORWARD_REWARD_WEIGHT: 1.0
  CTRL_COST_WEIGHT: 0.1
  RESET_NOISE_SCALE: 0.1
  USE_RELATIVE_OBS: False

EMAT:
  AGENT_NUM: 5
  N_TRAINING_THREADS: 15
  N_ROLLOUT_THREADS: 15
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

NETWORK:
  SHARE_POLICY: True
  USE_RELU: False
  HIDDEN_SIZE: 64
  LAYER_N: 2
  USE_CENTRALIZED_V: False

COMP:
  USE_COMPETITION: False
  COMPETITION_REWARD_COEF: 0.01 # 0.03

EVAL_PERIOD: 1