ENV_NAME: "MultiWalker2d-v0"
TEMPLATE: "./envs/assets/multi_walker2d.xml"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

ENV:
  EPISODE_LENGTH: 1000
  DIMENSION: 2
  FORWARD_REWARD_WEIGHT: 1.0
  CTRL_COST_WEIGHT: 1.e-3
  HEALTHY_REWARD: 1.0
  TERMINATE_WHEN_UNHEALTHY: True
  HEALTHY_Z_RANGE: (0.8, 2.0)
  HEALTHY_ANGLE_RANGE: (-1., 1.)
  RESET_NOISE_SCALE: 5.e-3
  USE_RELATIVE_OBS: True

EMAT:
  AGENT_NUM: 1
  N_TRAINING_THREADS: 15
  N_ROLLOUT_THREADS: 15
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

NETWORK:
  SHARE_POLICY: True
  USE_RELU: False
  HIDDEN_SIZE: 64
  LAYER_N: 2
  USE_CENTRALIZED_V: False

COMP:
  USE_COMPETITION: False
  COMPETITION_REWARD_COEF: 0.01 # 0.03

EVAL_PERIOD: 2