ENV_NAME: "MultiAnt-v0"
TEMPLATE: "./envs/assets/multi_ant.xml"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

ENV:
  EPISODE_LENGTH: 1600
  TERMINATE_WHEN_UNHEALTHY: True
  USE_RELATIVE_OBS: False

EMAT:
  AGENT_NUM: 3
  N_TRAINING_THREADS: 15
  N_ROLLOUT_THREADS: 15
  N_EVAL_ROLLOUT_THREADS: 1
  N_RENDER_ROLLOUT_THREADS: 1
  NUM_ENV_STEPS: 30e6

TEMPLATE: "./envs/assets/multi_ant.xml"

NETWORK:
  SHARE_POLICY: True
  USE_RELU: False
  HIDDEN_SIZE: 64
  USE_CENTRALIZED_V: False

COMP:
  USE_COMPETITION: True
  COMPETITION_REWARD_COEF: 0.1 # 0.03

EVAL_PERIOD: 1