ENV_NAME: "SumoEvoAnts-v0"

RNG_SEED: 42

USE_GPU: True
DEVICE: "cuda:0"

ENV:
  EPISODE_LENGTH: 500
  AGENT_NAMES: ['evo_ant_fighter', 'evo_ant_fighter']
  WORLD_XML_PATH: "./competevo/evo_envs/assets/world_body_arena.xml"