env_name: sumo-ants-v0
  
# training parameters
gamma: 0.995
tau: 0.95
policy_specs:
  name: v5
  htype: tanh
  control_mlp:
    hdims: [128, 128]
    rescale_linear: true
  control_log_std: 0
  attr_log_std: -2.3
  fix_control_std: false
  fix_attr_std: false
policy_optimizer: 'Adam'
policy_lr: 0.001 #5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_specs:
  htype: tanh
  mlp: [512, 256]
value_optimizer: 'Adam'
value_lr: 0.001 #3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 409600 #50000
mini_batch_size: 51200 #2048
num_optim_epoch: 6 #10
max_epoch_num: 2000
seed: 1
save_model_interval: 1

done_condition:
  max_ang: 60

use_reward_scaling: False
use_opponent_sample: False
use_shadow_sample: False
delta: 1.
use_exploration_curriculum: True
termination_epoch: 200