env_name: you-shall-not-pass-humans-v0
  
# training parameters
gamma: 0.995
tau: 0.95
policy_specs:
  name: v5
  htype: tanh
  control_mlp:
    hdims: [128, 128]
    rescale_linear: true
  control_log_std: 0
  attr_log_std: -2.3
  fix_control_std: false
  fix_attr_std: false
policy_optimizer: 'Adam'
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_specs:
  htype: tanh
  mlp: [512, 256]
value_optimizer: 'Adam'
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000 #50000
mini_batch_size: 2048
num_optim_epoch: 10
max_epoch_num: 1000
seed: 1
save_model_interval: 100

robot_param_scale: 1
skel_transform_nsteps: 5

done_condition:
  max_ang: 60

obs_specs:
  attr: ['depth']
  sim: []
  design: true
  clip_qvel: true
  use_projected_params: true
  use_body_ind: true
max_body_depth: 4

add_body_condition:
  max_nchild: 2

robot:
  param_mapping: sin
  no_root_offset: true
  
  body_params:
    offset:
      type: 'xy'
      lb: [-0.5, -0.5]
      ub: [0.5, 0.5]

  joint_params: {}

  geom_params:
    size:
      lb: 0.03
      ub: 0.10
    ext_start:
      lb: 0.0
      ub: 0.2

  actuator_params:
    gear:
      lb: 20
      ub: 400