algo: mappo
clip_param: 0.2
critic_lr: 0.0005
cuda_deterministic: true
data_chunk_length: 10
device: cuda:0
entropy_coef: 0.01
env_name: SumoEvoAnts-v0
episode_length: 1600
eval_episodes: 32
eval_interval: 25
gae_lambda: 0.95
gain: 0.01
gamma: 0.99
hidden_size: 64
huber_delta: 10
ifi: 0.01
layer_N: 2
log_interval: 1
lr: 0.0005
max_grad_norm: 10.0
n_eval_rollout_threads: 1
n_render_rollout_threads: 1
n_rollout_threads: 15
n_training_threads: 10
num_env_steps: 10000000
num_mini_batch: 1
opti_eps: 1.0e-05
ppo_epoch: 15
recurrent_N: 1
render_episodes: 1
robot:
  actuator_params:
    gear:
      lb: 20
      ub: 400
  body_params:
    offset:
      lb:
      - -0.5
      - -0.5
      type: xy
      ub:
      - 0.5
      - 0.5
  geom_params:
    ext_start:
      lb: 0.0
      ub: 0.2
    size:
      lb: 0.03
      ub: 0.1
  joint_params: {}
  no_root_offset: true
  param_mapping: sin
save_interval: 10
save_video: false
seed: 42
share_policy: false
stacked_frames: 1
use_ReLU: true
use_centralized_V: true
use_clipped_value_loss: true
use_eval: true
use_feature_normalization: true
use_gae: true
use_gpu: true
use_huber_loss: true
use_linear_lr_decay: false
use_max_grad_norm: true
use_naive_recurrent_policy: false
use_obs_instead_of_state: false
use_orthogonal: true
use_policy_active_masks: true
use_popart: false
use_proper_time_limits: false
use_recurrent_policy: false
use_render: false
use_stacked_frames: false
use_value_active_masks: true
use_valuenorm: true
use_wandb: false
user_name: competevo
value_loss_coef: 0.5
weight_decay: 0
