clip_epsilon: 0.2
delta: 0.0
done_condition:
  max_ang: 60
env_name: run-to-goal-ants-v0
gamma: 0.995
max_epoch_num: 1000
min_batch_size: 50000
mini_batch_size: 2048
num_optim_epoch: 10
policy_lr: 5.0e-05
policy_momentum: 0.0
policy_optimizer: Adam
policy_specs:
  attr_log_std: -2.3
  control_log_std: 0
  control_mlp:
    hdims:
    - 128
    - 128
    rescale_linear: true
  fix_attr_std: false
  fix_control_std: false
  htype: tanh
  name: v5
policy_weightdecay: 0.0
save_model_interval: 1
seed: 10
tau: 0.95
termination_epoch: 200
use_exploration_curriculum: true
use_opponent_sample: true
use_reward_scaling: false
value_lr: 0.0003
value_momentum: 0.0
value_optimizer: Adam
value_specs:
  htype: tanh
  mlp:
  - 512
  - 256
value_weightdecay: 0.0
